name: Fetch Tide Data

on:
  schedule:
    - cron: '0 2 * * *'  # Runs once daily at 02:00 UTC (~4am SAST)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-tides:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install node-fetch@2 cheerio

      - name: Run tide scraper
        run: node scripts/fetch-tides.js

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/tides.json
          git commit -m "Auto-update tides"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
