name: Fetch Weather Data

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-weather:
    runs-on: ubuntu-latest
    env:
      OWM_API_KEY: ${{ secrets.OWM_API_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install node-fetch
        run: npm install node-fetch@2

      - name: Fetch weather data
        run: node scripts/fetch-weather.js

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/weather.json
          git commit -m "Auto-update weather data"
          git push
